[package]
name = "aSynthe"
version = "0.1.2"
authors = ["tasuren <tasuren@aol.com>"]
edition = "2021"
description = "音程を検出するソフトです。"
readme = "README.md"
license-file = "LICENSE"
homepage = "https://tasuren.f5.si/downloads/asynthe.html"
repository = "https://github.com/tasuren/aSynthe"
keywords = ["application", "sound"]

[dependencies]
iui = { git = "https://github.com/rust-native-ui/libui-rs.git", branch = "trunk" }
ui-sys = { git = "https://github.com/rust-native-ui/libui-rs.git", branch = "trunk" }
native-dialog = "0.6.3"
lazy_static = "1.4.0"
rustfft = "6.0.1"
midir = "0.8.0"
cpal = "0.14.0"

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.9.3"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1.12"

[package.metadata.bundle]
name = "aSynthe"
identifier = "xyz.tasuren.asynthe"
icon = ["static/main.png"]
version = "0.1.0"
resources = ["static/notes.csv"]
copyright = "(c) tasuren 2022"
category = "public.app-category.utilities"
short_description = "音程を検出するためのソフトです。"
long_description = """音程を検出するためのソフトです。
あまり使い物になるようなものではないですが、MIDI出力にも対応しています。"""

[package.metadata.winres]
OriginalFilename = "aSynthe.exe"
LegalCopyright = "(c) tasuren 2022"