[package]
name = "aSynthe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iui = { git = "https://github.com/rust-native-ui/libui-rs.git", branch = "trunk" }
ui-sys = { git = "https://github.com/rust-native-ui/libui-rs.git", branch = "trunk" }
lazy_static = "1.4.0"
rustfft = "6.0.1"
midir = "0.8.0"
cpal = "0.13.5"